backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'images/cms_uploads'
public_folder: 'images/cms_uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home Page'
